In [21]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import cross_val_score

In [7]:
from sklearn.datasets import load_iris
iris = load_iris()
X = pd.DataFrame(iris.data,columns=iris.feature_names)
X

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                  5.1               3.5                1.4               0.2
1                  4.9               3.0                1.4               0.2
2                  4.7               3.2                1.3               0.2
3                  4.6               3.1                1.5               0.2
4                  5.0               3.6                1.4               0.2
..                 ...               ...                ...               ...
145                6.7               3.0                5.2               2.3
146                6.3               2.5                5.0               1.9
147                6.5               3.0                5.2               2.0
148                6.2               3.4                5.4               2.3
149                5.9               3.0                5.1               1.8

[150 rows x 4 columns]

In [15]:
y = iris.target
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [24]:
cross_val_score(LogisticRegression(max_iter=1000),X,y,cv=7)

array([0.95454545, 1.        , 0.90909091, 0.95238095, 0.95238095,
       1.        , 1.        ])

In [18]:
cross_val_score(SVC(),X,y,cv=7)

array([0.95454545, 1.        , 1.        , 0.95238095, 0.95238095,
       0.95238095, 1.        ])

In [20]:
cross_val_score(RandomForestClassifier(),X,y,cv=7)

array([0.95454545, 1.        , 0.90909091, 0.95238095, 0.85714286,
       1.        , 1.        ])

In [22]:
cross_val_score(DecisionTreeClassifier(),X,y,cv=7)

array([0.95454545, 1.        , 0.90909091, 0.85714286, 0.95238095,
       0.95238095, 1.        ])

In [29]:
print("Logistic Regression {} ".format(cross_val_score(LogisticRegression(max_iter=1000),X,y,cv=7).mean()))
print("Support Vector Machine {} ".format(cross_val_score(SVC(kernel='linear'),X,y,cv=7).mean()))
print("Random Forest {} ".format(cross_val_score(RandomForestClassifier(n_estimators=200),X,y,cv=7).mean()))
print("Decision Tree {} ".format(cross_val_score(DecisionTreeClassifier(),X,y,cv=7).mean()))

Logistic Regression 0.9669140383426098 
Support Vector Machine 0.9734075448361164 
Random Forest 0.9533085961657389 
Decision Tree 0.9400123685837972 
